### ISSUE TITLE
Issue with cards

### ISSUE THREAD

**Issue by ClaraCrazy** [JohnnyJayJay/poker#5]
im running into an issue with the bot.

the cards arent displayed. All I see is:

"Community Cards:
:: :: :: :: ::
:: :: :: :: ::
Main pot: 15 chips"

and I also see in the console that the bot is being rate-limited

**Comment by VerstreuteSeele** [comment]
update: found it however im running into an issue with the bot.

A: the cards arent displayed. All I see is:
Community Cards:
:: :: :: :: ::
:: :: :: :: ::
Main pot: 15 chips
and I also see in the console that the bot is being rate-limited

**Comment by JohnnyJayJay** [comment]
So, this is something I forgot to mention in the readme, but the bot uses custom emojis from one specific Discord server to display cards and the ids of those emojis have been hard-coded. Bots must be on the corresponding server to use custom emojis.\
You can either upload your own emojis and modify the ids in `poker.discord.display` accordingly, or you can join the [playing card emoji server](https://discord.gg/sJB2xjK) and ask the owner to add your bot.

**Comment by ClaraCrazy** [comment]
alright. thanks. What about the rate limiting? Is that caused by the cards not being there somehow? 

I will post a full log later. im currently not at home. All I remember is that it happened when doing holdem! and that it said to try again in 0.067 seconds.

**Comment by JohnnyJayJay** [comment]
I'm not sure what causes these exactly, I get them too when I run it on my local machine. Most likely you can safely ignore those warnings. Regardless, the app handles rate limits and retries stuff automatically, so with limits that low, this will barely be noticeable on the user end.

**Comment by ClaraCrazy** [comment]
alright 👍  think we can close this now
